const AID="hf7mcf9bv3nv8g5f", URL="https://frosty-leaf-0fc9.ricopbrunn.workers.dev";
let stop={name:"Marktplatz",id:null}, favorites=JSON.parse(localStorage.getItem("fav")||"[]"), deferredPrompt;

const base={ver:"1.81",lang:"deu",auth:{type:"AID",aid:AID},client:{id:"NASA",v:1000102,type:"WEB",name:"webapp"}};
async function hafas(req){const r=await fetch(URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...base, ...req})}); if(!r.ok) throw Error("INSA HTTP "+r.status); return r.json();}
function time(s){if(!s)return "–"; const x=String(s).replace(/^.*?(\d{2}):(\d{2}).*$/,"$1:$2"); return x.length===5?x:"–"}
function mins(t){if(!t)return null; const m=t.match(/T(\d{2}):(\d{2})/); if(!m)return null; const d=new Date(); const x=new Date(d.getFullYear(),d.getMonth(),d.getDate(),+m[1],+m[2]); let n=Math.round((x-d)/60000); if(n< -120)n+=1440; return n}
async function searchStops(){const q=document.getElementById("search").value.trim(); if(!q)return; const box=document.getElementById("results"); box.innerHTML="Suche …"; try{const data=await hafas({svcReqL:[{meth:"LocMatch",req:{input:{loc:{name:q},maxLoc:10}}}]}); const l=data.svcResL?.[0]?.res?.locL||[]; box.innerHTML=""; l.forEach(x=>{const b=document.createElement("button");b.textContent=x.name||"Haltestelle";b.onclick=()=>{stop={name:x.name,id:x.extId||x.id};box.innerHTML="";document.getElementById("stopName").textContent=stop.name;load();};box.appendChild(b)})}catch(e){box.innerHTML='<div class="error">INSA ist im Browser nicht erreichbar. Das kann an einer CORS-Sperre liegen.</div>'}}
async function load(){document.getElementById("status").textContent="Aktualisiere …"; try{const req={svcReqL:[{meth:"StationBoard",req:{stbLoc:{loc:stop.id?{extId:stop.id}:{name:stop.name}},dirLoc:null,duration:60,maxJny:15,boardType:"DEP"}}]}; const data=await hafas(req); const j=data.svcResL?.[0]?.res?.jnyL||[]; const box=document.getElementById("departures"); box.innerHTML=""; if(!j.length){box.innerHTML='<p class="muted">Keine Abfahrten gefunden.</p>'} j.forEach(x=>{const s=x.stbStop||{};const planned=s.dTimeS||s.dTime;const real=s.dTimeR||s.dTimeP;const tm=real||planned;const row=document.createElement("div");row.className="row";const tr=x.jny?.prod?.name||x.prod?.name||"–";const dest=x.jny?.dirTxt||x.jny?.dir||x.dirTxt||"–";const n=mins(tm);row.innerHTML=`<div class="line">${tr}</div><div class="dest">${dest}<div>${real?'<span class="rt">● Echtzeit</span>':''}</div></div><div><div class="time">${time(tm)}</div><div class="muted">${n==null?"":n<=0?"jetzt":n+" min"}</div></div>`;box.appendChild(row)});document.getElementById("status").textContent="Zuletzt aktualisiert: "+new Date().toLocaleTimeString("de-DE",{hour:"2-digit",minute:"2-digit"})}catch(e){document.getElementById("status").innerHTML='<span class="error">Keine Verbindung zur INSA-Schnittstelle. '+e.message+'</span>'}}
function tab(id,el){document.querySelectorAll("main>section").forEach(x=>x.classList.add("hidden"));document.getElementById(id).classList.remove("hidden");document.querySelectorAll(".tabs button").forEach(x=>x.classList.remove("active"));el.classList.add("active");if(id==="favorites")renderFav()}
function renderFav(){const box=document.getElementById("favList");box.innerHTML=favorites.length?favorites.map((x,i)=>`<button onclick="chooseFav(${i})">${x.name}</button>`).join(""):"<p class='muted'>Noch keine Favoriten.</p>"}
function chooseFav(i){stop=favorites[i];document.getElementById("stopName").textContent=stop.name;document.querySelector(".tabs button").click();load()}
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e});
async function installApp(){if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null}else alert("Nutze im Browser-Menü „Zum Startbildschirm hinzufügen“.")}
if("serviceWorker" in navigator) navigator.serviceWorker.register("sw.js");
load(); setInterval(load,30000);
